---
- name: Main
  hosts: '{{ target }}'
  gather_facts: false
  vars_files:
    - '{{ var_file }}'
  roles:
    - setup
    - node_install
    - node_initialize
    - node_configure
    - support_public_endpoints
    - node_launch
