---
- name: sort hosts
  hosts: networks
  gather_facts: no
  tasks:
  - group_by:
      key: seeds
    when: inventory_hostname.endswith('master')

  - name: change host to tenderseed
    set_fact:
      ansible_host: '{{ tenderseed_host }}'

- name: Install seed
  hosts: seeds
  gather_facts: false    
  roles:
    - setup
    - support_seed
