---
- name: Update peers in config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '^persistent_peers ='
    line: 'persistent_peers = "{{ peers }}"'
    state: present
  when: peers is defined

- name: Update seeds in config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '^seeds ='
    line: 'seeds = "{{ seeds }}"'
    state: present
  when: seeds is defined

- name: Open prometheus port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ custom_port_prefix }}60"
  when:
    - node_exporter|bool == true

- name: Open p2p port
  become: true
  ufw:
    rule: allow
    proto: tcp
    port: "{{ custom_port_prefix }}56"

- name: Open rpc port
  become: true
  ufw:
    rule: allow
    port: "{{ custom_port_prefix }}57"
  when: type is defined and type != 'main'

- name: Create cosmovisor directories
  command: "$BINARY_PATH/cosmovisor init $BINARY_PATH/{{ daemon }}"
  environment:
    - BINARY_PATH: '{{ user_dir }}/go/bin'
    - DAEMON_HOME: '{{ user_dir }}/{{ folder }}'
    - DAEMON_NAME: '{{ daemon }}'

- name: copy service file
  become: true
  template:
    src: 'cosmovisor.service.j2'
    dest: '/etc/systemd/system/{{ daemon }}.service'
    owner: root
    group: root
    mode: '0644'

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ daemon }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
