---
- name: Update peers in config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '^persistent_peers ='
    line: 'persistent_peers = "{{ peers }}"'
    state: present
  when: peers is defined

- name: Update seeds in config.toml file
  lineinfile:
    path: '{{ user_dir }}/{{ folder }}/config/config.toml'
    regexp: '^seeds ='
    line: 'seeds = "{{ seeds }}"'
    state: present
  when: seeds is defined

- name: open prometheus port
  become: true
  command: 'ufw allow {{ custom_port_prefix }}61/tcp'

- name: open p2p port
  become: true
  command: 'ufw allow {{ custom_port_prefix }}56/tcp'

- name: Create cosmovisor directories
  command: "$BINARY_PATH/cosmovisor init $BINARY_PATH/{{ daemon }}"
  environment:
    - BINARY_PATH: '{{ user_dir }}/go/bin'
    - DAEMON_HOME: '{{ user_dir }}/{{ folder }}'
    - DAEMON_NAME: '{{ daemon }}'

- name: copy service file
  become: true
  template:
    src: 'cosmovisor.service.j2'
    dest: '/etc/systemd/system/{{ network }}.service'
    owner: root
    group: root
    mode: '0644'

- name: start cosmovisor service
  become: true
  systemd:
    name: '{{ network }}'
    state: restarted
    daemon_reload: yes
    enabled: yes
