---
- name: register chain information
  uri:
    url: '{{ cosmos_directory_url }}/{{ network }}'
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  register: http_response

- name: consolidate http response to cosmos_directory api
  set_fact:
    cosmos_directory: '{{ http_response.json.chain }}'

- name: assign network variables
  set_fact:
    chain_id: '{{ chain_id | default(cosmos_directory.chain_id) }}'
    repo: '{{ git_repo | default(cosmos_directory.codebase.git_repo) }}'
    genesis: '{{ genesis | default(cosmos_directory.codebase.genesis.genesis_url) }}'
    network: '{{ network | default(cosmos_directory.name) }}'
    folder: '{{ folder | default(cosmos_directory.node_home) | replace("$HOME/", "") }}'
    node_version: '{{ node_version | default(cosmos_directory.codebase.recommended_version) }}'
    daemon: '{{ daemon | default(cosmos_directory.daemon_name) }}'
    seeds: '{{ seeds | default("") }}'  

- name: define minimum gas prices
  block:
    - name: assign minimum gas vars
      set_fact:
        denom: '{{ cosmos_directory.fees.fee_tokens[0].denom }}'
        minimum_fee: '{{ cosmos_directory.fees.fee_tokens[0].fixed_min_gas_price }}'

    - name: set minimum gas price
      set_fact:
        minimum_gas_price: '{{ minimum_fee|string + denom }}'
  when: minimum_gas_price is not defined
  ignore_errors: true

- name: build seed string
  set_fact:
    seeds: '{{ item.id }}@{{ item.address }},{{ seeds }}'
  with_items: 
    - '{{ cosmos_directory.peers.seeds }}'

- name: cut trailing comma
  set_fact:
    seeds: '{{ seeds.rstrip(",") }}'

- name: override node_version with upgrade
  set_fact:
    node_version: '{{ upgrade_version }}'
  when: upgrade_version is defined