---
- name: get chain registry info
  import_tasks: get_chain_registry_info.yml

- name: get custom port prefix
  import_tasks: get_port_prefix.yml

- name: assign testnet vars
  include_vars: 'group_vars/testnets/{{ testnet_vars }}'
  when: 'type == "testnet"'
