---
- name: get port prefixes
  uri:
    url: '{{ port_prefix_url }}'
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  register: port_prefixes
  when: port_prefix_url is defined
  run_once: true

- name: set response as json
  set_fact:
    prefixes: '{{ port_prefixes.content | from_json }}'
  when: port_prefix_url is defined

- name: register chain information
  uri:
    url: '{{ cosmos_directory_url }}/{{ network }}'
    method: GET
    return_content: true
    status_code: 200
    body_format: json
  register: http_response
  when: cosmos_directory_url is defined

- name: consolidate http response to cosmos_directory api
  set_fact:
    cosmos_directory: '{{ http_response.json.chain }}'

- name: define network variables
  set_fact:
    custom_port_prefix: '{{ prefixes[network] }}'
    chain_id: '{{ cosmos_directory.chain_id }}'
    repo: '{{ cosmos_directory.codebase.git_repo }}'
    genesis: '{{ cosmos_directory.genesis.genesis_url }}'
    network: '{{ cosmos_directory.name }}'
    folder: '{{ cosmos_directory.node_home | replace("$HOME/", "") }}'
    node_version: '{{ cosmos_directory.codebase.recommended_version }}'
    daemon: '{{ cosmos_directory.daemon_name }}'
    seeds: ''

- name: override node_version
  set_fact:
    node_version: '{{ upgrade_version }}'
  when: upgrade_version is defined

- name: build seed string
  set_fact:
    seeds: '{{ item.id }}@{{ item.address }},{{ seeds }}'
  with_items: 
    - '{{ cosmos_directory.peers.seeds }}'

- name: cut trailing comma
  set_fact:
    seeds: '{{ seeds.rstrip(",") }}'
